# Pre-commit hooks for Shimmy
# Ensures code quality before commits reach the repository

repos:
  # Rust-specific quality checks
  - repo: local
    hooks:
      # Rust formatting check
      - id: cargo-fmt
        name: Cargo format check
        entry: cargo fmt -- --check
        language: system
        files: \.rs$
        pass_filenames: false

      # Rust linting with clippy
      - id: cargo-clippy
        name: Cargo clippy linting
        entry: cargo clippy --all-features -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false

      # Rust tests with all features
      - id: cargo-test-all-features
        name: Cargo test all features
        entry: cargo test --all-features
        language: system
        files: \.rs$
        pass_filenames: false

  # Git hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Prevent commits directly to main branch
      - id: no-commit-to-branch
        args: ['--branch', 'main']
        
      # Quality gates must pass (excluding templates that intentionally have multiple YAML docs)
      - id: check-toml

  # Documentation validation
  - repo: local
    hooks:
      - id: docs-updated
        name: Documentation update check
        entry: echo "Remember to update documentation with code changes"
        language: system
        files: \.rs$
        pass_filenames: false
        verbose: true