name: Feature Request
description: Suggest an idea for Shimmy
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - Michael-A-Kuykendall

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please check our [ROADMAP.md](../ROADMAP.md) first to see if it's already planned.

  - type: checkboxes
    id: alignment
    attributes:
      label: Feature Alignment
      description: Does this feature align with Shimmy's philosophy?
      options:
        - label: This feature maintains the lightweight (~5MB) binary target
          required: true
        - label: This feature supports zero-config, invisible infrastructure
          required: true
        - label: This feature enhances OpenAI API compatibility
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: Describe the pain point this would address
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/blocking
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples