#!/usr/bin/env node

/**
 * Generate TypeScript definitions from an orchestrator export or /__shimmy__/schema
 * 
 * This script reads the JSON schema generated by fetching the orchestrator
 * endpoint `/__shimmy__/schema` (or a local exported schema file) and converts
 * it to TypeScript type definitions for use in frontend themes.
 */

const fs = require('fs');
const path = require('path');
const { compile } = require('json-schema-to-typescript');

// Default file written by the orchestrator export flow (CI/artifact friendly)
const SCHEMA_FILE = 'exported-shimmy-schema.json';
const OUTPUT_DIR = 'theme-types';
const OUTPUT_FILE = 'shimmy-contract.d.ts';

/**
 * Transform Shimmy contract schema to proper JSON Schema format
 */
function transformShimmySchemaToJsonSchema(shimmySchema) {
  const jsonSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'Shimmy Frontend Contract',
    description: shimmySchema.description || 'Shimmy Frontend Contract Schema',
    type: 'object',
    properties: {
      version: { type: 'string', description: 'Contract version' },
      description: { type: 'string', description: 'Schema description' },
      discovery: {
        type: 'object',
        description: 'Discovery service configuration',
        properties: {
          endpoint: { type: 'string', description: 'Discovery endpoint path' },
          port: { type: 'number', description: 'Default discovery port' },
          validation_fields: {
            type: 'array',
            items: { type: 'string' },
            description: 'Required validation fields'
          },
          backend_resolve_timeout_ms: { type: 'number', description: 'Backend resolution timeout' }
        },
        required: ['endpoint', 'port'],
        additionalProperties: false
      },
      websocket_messages: {
        type: 'array',
        description: 'WebSocket message definitions',
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', description: 'Message name' },
            type: { type: 'string', enum: ['request', 'response'], description: 'Message type' },
            description: { type: 'string', description: 'Message description' },
            schema: { type: 'object', description: 'JSON Schema for message payload' }
          },
          required: ['name', 'type', 'schema'],
          additionalProperties: false
        }
      },
      streaming: {
        type: 'object',
        description: 'Streaming configuration',
        properties: {
          supported: { type: 'boolean', description: 'Whether streaming is supported' },
          endpoints: {
            type: 'object',
            description: 'Streaming endpoint paths',
            additionalProperties: { type: 'string' }
          },
          message_format: { type: 'string', description: 'Message format (e.g., "json")' },
          heartbeat_interval_ms: { type: 'number', description: 'Heartbeat interval in milliseconds' }
        },
        required: ['supported'],
        additionalProperties: false
      },
      http_endpoints: {
        type: 'array',
        description: 'HTTP endpoint definitions',
        items: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Endpoint path' },
            method: { type: 'string', description: 'HTTP method' },
            description: { type: 'string', description: 'Endpoint description' }
          },
          required: ['path', 'method'],
          additionalProperties: false
        }
      },
      required_behaviors: {
        type: 'array',
        items: { type: 'string' },
        description: 'Required frontend behaviors'
      },
      ui_requirements: {
        type: 'object',
        description: 'UI requirements',
        properties: {
          responsive: { type: 'boolean', description: 'Responsive design requirement' },
          accessibility: { type: 'string', description: 'Accessibility standard' },
          performance: { type: 'string', description: 'Performance requirements' },
          themes: {
            type: 'array',
            items: { type: 'string' },
            description: 'Supported themes'
          }
        },
        additionalProperties: false
      }
    },
    required: ['version', 'discovery', 'websocket_messages', 'streaming', 'http_endpoints'],
    additionalProperties: false
  };

  // Include the definitions section if it exists
  if (shimmySchema.definitions) {
    jsonSchema.definitions = shimmySchema.definitions;
    
    // Also create top-level interfaces for each definition
    Object.keys(shimmySchema.definitions).forEach(defName => {
      jsonSchema.properties[defName] = {
        $ref: `#/definitions/${defName}`,
        description: `Reference to ${defName} definition`
      };
    });
  }

  return jsonSchema;
}

async function fetchSchemaFromUrl(url) {
  return new Promise((resolve, reject) => {
    try {
      const parsed = new URL(url);
      const lib = parsed.protocol === 'https:' ? require('https') : require('http');
      const opts = { headers: { 'User-Agent': 'shimmy-generate-types' } };

      lib.get(url, opts, res => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          // follow redirect
          return resolve(fetchSchemaFromUrl(res.headers.location));
        }

        if (res.statusCode !== 200) {
          return reject(new Error(`Failed to fetch schema: HTTP ${res.statusCode}`));
        }

        let data = '';
        res.setEncoding('utf8');
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          try {
            const obj = JSON.parse(data);
            resolve(obj);
          } catch (err) {
            reject(new Error('Invalid JSON received from schema URL'));
          }
        });
      }).on('error', reject);

    } catch (err) {
      reject(err);
    }
  });
}

async function generateTypes() {
  try {
    console.log('🔄 Generating TypeScript types from Shimmy contract schema...');
    
    // Determine schema source: env SHIMMY_SCHEMA_URL, CLI --source <url>, or local file
    const envUrl = process.env.SHIMMY_SCHEMA_URL;
    let sourceUrl = null;

    const idx = process.argv.indexOf('--source');
    const shortIdx = process.argv.indexOf('-s');
    if (idx !== -1 && process.argv.length > idx + 1) {
      sourceUrl = process.argv[idx + 1];
    } else if (shortIdx !== -1 && process.argv.length > shortIdx + 1) {
      sourceUrl = process.argv[shortIdx + 1];
    } else if (envUrl) {
      sourceUrl = envUrl;
    }

    let schema = null;

    if (sourceUrl) {
      console.log(`🌐 Fetching schema from source: ${sourceUrl}`);
      try {
        schema = await fetchSchemaFromUrl(sourceUrl);
      } catch (err) {
        console.error(`❌ Failed to fetch schema from ${sourceUrl}: ${err.message}`);
        process.exit(1);
      }
    } else {
      // Fallback to local file
      if (!fs.existsSync(SCHEMA_FILE)) {
        console.error(`❌ Schema file ${SCHEMA_FILE} not found!`);
        console.error('   Run an orchestrator export or set SHIMMY_SCHEMA_URL / --source to point at /__shimmy__/schema');
        process.exit(1);
      }

      // Read and parse schema
      const schemaContent = fs.readFileSync(SCHEMA_FILE, 'utf8');
      try {
        schema = JSON.parse(schemaContent);
      } catch (parseError) {
        console.error(`❌ Invalid JSON in ${SCHEMA_FILE}:`);
        console.error(parseError.message);
        process.exit(1);
      }
    }
    
    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
      console.log(`📁 Created directory: ${OUTPUT_DIR}/`);
    }
    
    // Configure compilation options
    const options = {
      bannerComment: '',
      style: {
        bracketSpacing: true,
        printWidth: 120,
        semi: true,
        singleQuote: true,
        tabWidth: 2,
        trailingComma: 'es5',
        useTabs: false,
      },
      additionalProperties: false,
      enableConstEnums: true,
      format: true,
      ignoreMinAndMaxItems: false,
      maxItems: 20,
      strictIndexSignatures: false,
      unreachableDefinitions: false,
    };
    
    // Add JSDoc comments from schema descriptions
    if (schema.description) {
      options.bannerComment = `/**\n * ${schema.description}\n * \n * Auto-generated from orchestrator export (exported-shimmy-schema.json)\n * Do not edit this file manually - regenerate using: npm run generate-types\n */`;
    } else {
      options.bannerComment = `/**\n * Shimmy Frontend Contract Types\n * \n * Auto-generated from orchestrator export (exported-shimmy-schema.json)\n * Do not edit this file manually - regenerate using: npm run generate-types\n */`;
    }
    
    // Transform the schema to proper JSON Schema format
    console.log('🔄 Transforming schema to JSON Schema format...');
    const transformedSchema = transformShimmySchemaToJsonSchema(schema);
    
    // Generate TypeScript definitions
    console.log('🔨 Compiling JSON Schema to TypeScript...');
    const typescript = await compile(transformedSchema, 'ShimmyFrontendContract', options);
    
    // Write to output file
    const outputPath = path.join(OUTPUT_DIR, OUTPUT_FILE);
    fs.writeFileSync(outputPath, typescript);
    
    console.log(`✅ TypeScript definitions generated successfully!`);
    console.log(`   Output: ${outputPath}`);
    console.log(`   Size: ${(typescript.length / 1024).toFixed(1)} KB`);
    
    // Validate the generated types can compile
    console.log('🧪 Testing generated types...');
    const { execSync } = require('child_process');
    
    try {
      execSync(`npx tsc --noEmit "${outputPath}"`, { stdio: 'pipe' });
      console.log('✅ Generated types compile successfully!');
    } catch (compileError) {
      console.warn('⚠️  Generated types have compilation warnings:');
      console.warn(compileError.stdout?.toString() || compileError.message);
    }
    
    // Show type summary
    const typeCount = (typescript.match(/interface\s+\w+/g) || []).length;
    const enumCount = (typescript.match(/enum\s+\w+/g) || []).length;
    
    console.log('\n📊 Generation Summary:');
    console.log(`   • ${typeCount} interfaces generated`);
    console.log(`   • ${enumCount} enums generated`);
    console.log(`   • Schema version: ${schema.version || 'unknown'}`);
    
    if (schema.properties) {
      const topLevelProps = Object.keys(schema.properties);
      console.log(`   • Top-level properties: ${topLevelProps.join(', ')}`);
    }
    
    console.log('\n✨ Contract types are ready for use in frontend themes!');
    
  } catch (error) {
    console.error('❌ Error generating TypeScript types:');
    console.error(error.message);
    
    if (error.stack) {
      console.error('\nStack trace:');
      console.error(error.stack);
    }
    
    process.exit(1);
  }
}

// Show help if requested
  if (process.argv.includes('--help') || process.argv.includes('-h')) {
  console.log(`
TypeScript Contract Generator for Shimmy

Usage:
  node scripts/generate-types.js [options]

Options:
  -h, --help     Show this help message

  Files:
  Input:  ${SCHEMA_FILE}  OR fetch from --source <url> or env SHIMMY_SCHEMA_URL
  Output: ${OUTPUT_DIR}/${OUTPUT_FILE}

This script converts the JSON schema produced by the orchestrator's `/__shimmy__/schema` into
TypeScript type definitions for use in Shimmy frontend themes.

Example workflow:
  1. Use the orchestrator endpoint `/__shimmy__/schema` and pass it to this script
     via --source or SHIMMY_SCHEMA_URL, e.g.:
       node scripts/generate-types.js --source http://127.0.0.1:11430/__shimmy__/schema
     or:
       SHIMMY_SCHEMA_URL=http://127.0.0.1:11430/__shimmy__/schema npm run generate-types
  2. npm run generate-types   # Generate TypeScript types (this script)
  3. npm run test-types      # Validate generated types compile
`);
  process.exit(0);
}

// Run the generator
if (require.main === module) {
  generateTypes();
}

module.exports = { generateTypes };